### ISSUE TITLE
App crash when click in analytics 

### ISSUE THREAD

**Issue by ehsan58** [Futsch1/medTimer#199] opened 2024-07-24 04:39 UTC
Hello, I am experiencing an issue with the app after the recent update. When I click on the analytics tab, the app unfortunately crashes. Could you please look into this matter and provide a solution? Thank you for your attention to this issue.
i did clear cache many times but nothing changed
https://github.com/user-attachments/assets/ad32fd5c-b80b-4db0-88c7-4288edd68231

**Comment by Futsch1** [comment] 2024-07-24 06:48
There is an event in the list that is dated to 2080 - this does not look right.

For me to debug this it would be great if you could send me a mail with your event backup json (if this is ok for you since it contains sensitive data).

You could also try to remove the broken event on the backup file using a text editor and restore it afterwards. 

I will try to reproduce and look into it.

**Comment by ehsan58** [comment] 2024-07-24 06:53
> There is an event in the list that is dated to 2080 - this does not look right.
> 
> For me to debug this it would be great if you could send me a mail with your event backup json (if this is ok for you since it contains sensitive data).
> 
> You could also try to remove the broken event on the backup file using a text editor and restore it afterwards. 
> 
> I will try to reproduce and look into it.

No problem please send me your email

**Comment by Futsch1** [comment] 2024-07-24 06:55
It's ***@***.***

Ehsan Mozaffari ***@***.***> schrieb am Mi., 24. Juli 2024,
08:53:

**Comment by Futsch1** [comment] 2024-07-24 06:56
It's florian.fetz@googlemail.com

**Comment by Futsch1** [comment] 2024-07-24 20:08
Can reproduce it and found the cause, will be fixed in next release.

**Closed** 2024-07-24 20:36 UTC
Labels: bug
